mongodb/docs-cpp

- source/getting-help.txt
- source/installation.txt
- source/installation/windows.txt
- source/polyfill-selection.txt
The API and ABI Versioning updates will be addressed as a [separate ticket](https://jira.mongodb.org/browse/DOCSP-37650).
Original PR - https://github.com/mongodb/docs-cpp/pull/4
Staging:
- https://docs-mongodbcom-staging.corp.mongodb.com/cpp-driver/docsworker-xlarge/dev-content-review/polyfill-selection/
- https://docs-mongodbcom-staging.corp.mongodb.com/cpp-driver/docsworker-xlarge/dev-content-review/getting-help/
- https://docs-mongodbcom-staging.corp.mongodb.com/cpp-driver/docsworker-xlarge/dev-content-review/installation/
- https://docs-mongodbcom-staging.corp.mongodb.com/cpp-driver/docsworker-xlarge/dev-content-review/installation/windows/
> Dev review of initial content

- source/facets.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-35438>
Staging - <https://preview-mongodbsarahemlin.gatsbyjs.io/cpp-driver/DOCSP-35438/>
Build log - <https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65f225686fc5f0485042d7d9>
Someone added a facet.toml file manually, but it was incorrect.  The tagging script has updated the file as it should be.
> DOCSP-35438 programmatic tagging script for cpp driver repo

- source/facets.toml
- source/getting-help.txt
- source/installation.txt
- source/installation/windows.txt
- source/polyfill-selection.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-35153>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/cpp-driver/docsworker-xlarge/v3.10/>
> Update facets script and incorporate tech review for v3.10

- config/redirects
- snooty.toml
- source/api-abi-versioning.txt
- source/api-abi-versioning/abi-versioning.txt
- source/api-abi-versioning/api-versioning.txt
Replaces https://github.com/mongodb/mongo-cxx-driver/pull/1102
JIRA:
- https://jira.mongodb.org/browse/DOCSP-37650 
- Original: https://jira.mongodb.org/browse/CXX-2967
Staging:
- [API and ABI Versioning](https://docs-mongodbcom-staging.corp.mongodb.com/cpp-driver/docsworker-xlarge/DOCSP-37650/api-abi-versioning/)
- [ABI Versioning](https://docs-mongodbcom-staging.corp.mongodb.com/cpp-driver/docsworker-xlarge/DOCSP-37650/api-abi-versioning/abi-versioning/)
- [API Versioning](https://docs-mongodbcom-staging.corp.mongodb.com/cpp-driver/docsworker-xlarge/DOCSP-37650/api-abi-versioning/api-versioning/)
> [C++] Document the Stable ABI Compatibility Policy

- config/redirects
Change cpp url from `/docs/languages/cpp/drivers` to `/docs/languages/cpp/cpp-driver`.
> Change cpp url to `/docs/languages/cpp/cpp-driver`

- source/connect.txt
- source/connect/client.txt
- source/connect/instance.txt
- source/includes/assumes-instance.rst
- source/includes/connect.cpp
- source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-40785
Staging - https://preview-mongodbmongokart.gatsbyjs.io/cpp-driver/docsp-40785-create-client/connect/instance/
> DOCSP-40785 - Create Instance and Client

- source/includes/read/distinct.cpp
- source/read.txt
- source/read/distinct.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-40802
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/cpp-driver/DOCSP-40802-distinct/read/distinct/
> DOCSP-40802: Distinct values

- source/configuration.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-41216
Staging - https://preview-mongodbmongokart.gatsbyjs.io/cpp-driver/docsp-41216-broken-link/configuration/#compressing-data-to-and-from-mongodb
> DOCSP-41216 - Broken link

- source/includes/read/cursor.cpp
- source/read.txt
- source/read/cursor.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-40803
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/cpp-driver/DOCSP-40803-cursor-guide/read/cursor/
> DOCSP-40803: Cursor guide

- source/includes/read/change-streams.cpp
- source/read.txt
- source/read/change-streams.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-40804
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/cpp-driver/DOCSP-40804-monitor-changes/read/change-streams/
> DOCSP-40804: Monitor changes

- snooty.toml
- source/includes/usage-examples/read-code-examples.cpp
- source/includes/usage-examples/sample-app-intro.rst
- source/includes/usage-examples/sample-app.cpp
- source/read.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-40796
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/cpp-driver/DOCSP-40796-read-landing/read/
> DOCSP-40796: Read operations landing

- snooty.toml
- source/includes/indexes/indexes.cpp
- source/index.txt
- source/indexes.txt
- source/work-with-indexes.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-40806
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/cpp-driver/DOCSP-40806-indexes/work-with-indexes/
> DOCSP-40806 Indexes

- source/includes/write/delete.cpp
- source/write.txt
- source/write/delete.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-40792
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/cpp-driver/DOCSP-40792-delete/write/delete/
> DOCSP-40792: Delete guide

- source/includes/write/update.cpp
- source/write.txt
- source/write/update.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-40793
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/cpp-driver/DOCSP-40793-update/write/update/
> DOCSP-40793: Update guide

- source/includes/write/bulk-write.cpp
- source/write.txt
- source/write/bulk-write.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-40794
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/cpp-driver/DOCSP-40794-bulk-write/write/bulk-write/#customize-bulk-write-operations
> DOCSP-40794: Bulk write guide

- snooty.toml
- source/includes/usage-examples/write-code-examples.cpp
- source/read.txt
- source/write.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-40790
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/cpp-driver/DOCSP-40790-write-landing/write/
> DOCSP-40790: Write operations landing page

- source/data-formats.txt
- source/data-formats/time-series.txt
- source/includes/data-formats/time-series.cpp
- source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-40815
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/cpp-driver/DOCSP-40815-time-series/data-formats/time-series/
> DOCSP-40815: Time series

- snooty.toml
- source/data-formats.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-40813
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/cpp-driver/DOCSP-40813-data-landing/data-formats/
> DOCSP-40813: Data formats landing page

- source/aggregation.txt
- source/includes/aggregation.cpp
- source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-40809
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/cpp-driver/DOCSP-40809-aggregation/aggregation/
> DOCSP-40809: Aggregation guide

- source/includes/aggregation.cpp
- source/includes/connect/atlas.cpp
- source/includes/connect/client.cpp
- source/includes/connect/direct-connection.cpp
- source/includes/connect/instance.cpp
- source/includes/connect/replica-set.cpp
- source/includes/data-formats/time-series.cpp
- source/includes/get-started/quickstart.cpp
- source/includes/read/change-streams.cpp
- source/includes/read/count.cpp
- source/includes/read/cursor.cpp
- source/includes/read/distinct.cpp
- source/includes/read/limit-skip-sort.cpp
- source/includes/read/project.cpp
- source/includes/read/retrieve.cpp
- source/includes/read/specify-queries.cpp
- source/includes/usage-examples/read-code-examples.cpp
- source/includes/usage-examples/sample-app.cpp
- source/includes/usage-examples/write-code-examples.cpp
- source/includes/write/bulk-write.cpp
- source/includes/write/delete.cpp
- source/includes/write/insert.cpp
- source/includes/write/update.cpp
Removing brackets when creating an `instance` based on updated guidance from engineering
JIRA - N/A
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/cpp-driver/update-create-instance/
> Remove brackets from instances

- source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-40817
Staging - https://preview-mongodbmongokart.gatsbyjs.io/cpp-driver/docsp-40817-api-link/
> DOCSP-40817 - API Link

- source/configuration.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-41676
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/cpp-driver/DOCSP-41676-config-option/configuration/#x.509
- [N/A] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?
> DOCSP-41676 Update TLS Config option

- source/connect.txt
- source/connect/connection-options.txt
- source/connect/network-compression.txt
- source/includes/connect/network-compression.cpp
Adapted from the [PyMongo page](https://www.mongodb.com/docs/languages/python/pymongo-driver/current/connect/network-compression/) on the same topic 
JIRA - https://jira.mongodb.org/browse/DOCSP-40788
Staging - https://preview-mongodbmongokart.gatsbyjs.io/cpp-driver/docsp-40788-compression/connect/network-compression/
> DOCSP-40788 - Network Compression

- snooty.toml
- source/connect.txt
- source/connect/connection-targets.txt
- source/includes/usage-examples/connect-code-examples.cpp
JIRA - https://jira.mongodb.org/browse/DOCSP-40784
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/cpp-driver/DOCSP-40784-connect/connect/
**Note to reviewer**: some of the code examples won't render yet, since they pull from .rst files added in [the open TLS PR](https://github.com/mongodb/docs-cpp/pull/50/files). I won't merge this PR until after TLS is completed.
> DOCSP-40784: Connect landing page

- source/index.txt
- source/whats-new.txt
Taken from [these driver release notes](https://github.com/mongodb/mongo-cxx-driver/releases)
JIRA - https://jira.mongodb.org/browse/DOCSP-40818
Staging - https://preview-mongodbmongokart.gatsbyjs.io/cpp-driver/docsp-40818-whats-new/whats-new/
> DOCSP-40818 - What's New

- source/connect/client.txt
- source/includes/authentication.cpp
- source/security/authentication.txt
- source/security/enterprise-authentication.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-42382
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/cpp-driver/DOCSP-42382-username-password/
> DOCSP-42382: Update connection string placeholders

- config/redirects
JIRA - https://jira.mongodb.org/browse/DOCSP-42783
Redirects -
For new docs -> old docs:
Redirect 301 /docs/languages/cpp/cpp-driver/v3.10/get-started/ https://www.mongodb.com/docs/languages/cpp/cpp-driver/v3.10/
Redirect 301 /docs/languages/cpp/cpp-driver/v3.10/connect/ https://www.mongodb.com/docs/languages/cpp/cpp-driver/v3.10/installation/
Redirect 301 /docs/languages/cpp/cpp-driver/v3.10/read/ https://www.mongodb.com/docs/languages/cpp/cpp-driver/v3.10/
Redirect 301 /docs/languages/cpp/cpp-driver/v3.10/write/ https://www.mongodb.com/docs/languages/cpp/cpp-driver/v3.10/
Redirect 301 /docs/languages/cpp/cpp-driver/v3.10/indexes/ https://www.mongodb.com/docs/languages/cpp/cpp-driver/v3.10/
Redirect …
> DOCSP-42783: Add redirects

- config/redirects
JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>
> Redirects fix 2

- source/includes/indexes/indexes.cpp
- source/includes/usage-examples/index-code-examples.cpp
- source/indexes.txt
- source/indexes/atlas-search-index.txt
- source/indexes/work-with-indexes.txt
- source/read/retrieve.txt
- source/write/replace.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-40808>
Staging - <https://deploy-preview-72--docs-cpp.netlify.app/indexes/atlas-search-index/>
> DOCSP-40808 v3.11 backport

- source/read/change-streams.txt
- source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45315
Staging - https://deploy-preview-76--docs-cpp.netlify.app/whats-new/#what-s-new-in-4.0
> DOCSP-45315: start_at_operation_time getter

- source/get-started/download-and-install.txt
- source/upgrade.txt
- source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45309
Staging:
https://deploy-preview-75--docs-cpp.netlify.app/whats-new/#what-s-new-in-4.0
https://deploy-preview-75--docs-cpp.netlify.app/upgrade/#version-4.0
> DOCSP-45309: CMake option changes

- .github/workflows/vale-tdbx.yml
- source/read/retrieve.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45765
> DOCSP-45765: Fix Vale check

- source/upgrade.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45596>
Staging - <https://deploy-preview-86--docs-cpp.netlify.app/upgrade/>
> DOCSP-45596-fix-text-overlap

- source/includes/write/transactions.cpp
- source/write.txt
- source/write/transactions.txt
* (DOCSP-45012) Added file.
* (DOCSP-45012) Added methods to page.
* (DOCSP-45012) Added code.
* (DOCSP-45012) Edits.
* (DOCSP-45012) Fix list formatting.
* (DOCSP-45012) Fix list formatting.
* (DOCSP-45012) Added examples for manual transactions and moved transactions page under Write.
* (DOCSP-45012) Edits.
* (DOCSP-45012) Edits.
* (DOCSP-45012) Edits.
* (DOCSP-45012) Edits.
* (DOCSP-45012) Edits.
* (DOCSP-45012) Editing instructions for transactions.
* (DOCSP-45012) Edits.
* (DOCSP-45012) Formatting.
* (DOCSP-45012) Wording.
* (DOCSP-45012) Edit introduction to code examples.
* (DOCSP-45012) Edit.
* (DOCSP-45012) Edits.
* (DOCSP-45012) Edits>
* (DOCSP-45012) Edits.
* (DOCSP-45012) Fix links.g
* (DOCSP-45012) Edits + vale fix.
* (DOCSP-45012) Vale error fix.
* (DOCSP-45012) Edit.
* …
> (DOCSP-45012) Backport Transactions (#71)

- source/upgrade.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43248>
Staging - <https://deploy-preview-90--docs-cpp.netlify.app/upgrade/#version-3.11>
> DOCSP-43248-upgrade-catch2-library

- source/data-formats/working-with-bson.txt
- source/includes/data-formats/bson.cpp
Standardize the Specialized Data Formats > BSON page in the C++ documentation. 
JIRA - <https://jira.mongodb.org/browse/DOCSP-40814>
Staging - <https://deploy-preview-81--docs-cpp.netlify.app/data-formats/working-with-bson/>
> (DOCSP-40814) [C++] Specialized Data Formats > BSON 

- source/write/transactions.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45869>
Staging - <https://deploy-preview-94--docs-cpp.netlify.app/write/transactions/>
> [C++] Add note about parallel operations

- source/connect/connection-pools.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45283
<li><a href=https://deploy-preview-99--docs-cpp.netlify.app/connect/connection-pools>connect/connection-pools</a></li>
> [C++] Remove minPoolSize

- source/connect/connection-pools.txt
- source/thread-safety.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45289>
<li><a href=https://deploy-preview-100--docs-cpp.netlify.app/connect/connection-pools>connect/connection-pools</a></li><li><a href=https://deploy-preview-100--docs-cpp.netlify.app/thread-safety>thread-safety</a></li>
> [C++] Document connection pool vs process fork order

- source/index.txt
- source/read.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48025>
<li><a href=https://deploy-preview-103--docs-cpp.netlify.app/index>index</a></li><li><a href=https://deploy-preview-103--docs-cpp.netlify.app/read>read</a></li>
> [C++] Remove "MongoDB" from page title

- .github/workflows/vale-tdbx.yml
- source/index.txt
- source/read.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48025>
From https://github.com/mongodb/docs-cpp/pull/103
> [C++] Backport title fix to v4.0

- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48213>
<li><a href=https://deploy-preview-106--docs-cpp.netlify.app/whats-new>whats-new</a></li>
> DOCSP-48213 - Index definitions 404

- source/connect/connection-targets.txt
- source/get-started.txt
- source/security/authentication.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48710>
also fixed a rendering issue with bolding in the get started page, unrelated to user/pw info
<li><a href=https://deploy-preview-112--docs-cpp.netlify.app/connect/connection-targets>connect/connection-targets</a></li><li><a href=https://deploy-preview-112--docs-cpp.netlify.app/get-started>get-started</a></li><li><a href=https://deploy-preview-112--docs-cpp.netlify.app/security/authentication>security/authentication</a></li>
> DOCSP-48710 change user/pw info

- .github/pull_request_template.md
JIRA - <https://jira.mongodb.org/browse/DOCSP-48930>
No pages to preview
> [C++] Add a PR checklist item for checking page titles

- source/get-started.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-49142>
<li><a href=https://deploy-preview-118--docs-cpp.netlify.app/get-started>get-started</a></li>
> DOCSP-49142 - Remove duplicate H1s

- config/redirects
Fix for multiple pages having the same title due to missing redirects
JIRA - https://jira.mongodb.org/browse/DOCSP-49134
No staging changes
> DOCSP-49134 Duplicate title fix

- source/connect/connection-targets.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48754>
<li><a href=https://deploy-preview-122--docs-cpp.netlify.app/connect/connection-targets>connect/connection-targets</a></li>
> DOCSP-48754: Docker note

- source/connect.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-48547
<li><a href=https://deploy-preview-123--docs-cpp.netlify.app/connect>connect</a></li>
> DOCSP-48547 Add AWS Lambda link

- source/advanced-installation.txt
- source/includes/libmongoc-compatibility-table-cxx.rst
- source/upgrade.txt
- source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-49398
<li><a href=https://deploy-preview-130--docs-cpp.netlify.app/advanced-installation>advanced-installation</a></li><li><a href=https://deploy-preview-130--docs-cpp.netlify.app/upgrade>upgrade</a></li><li><a href=https://deploy-preview-130--docs-cpp.netlify.app/whats-new>whats-new</a></li>
> DOCSP-49398: C driver 2.0 requirement

- source/get-started.txt
- source/includes/get-started/quickstart.cpp
- source/includes/read/retrieve.cpp
- source/includes/usage-examples/read-code-examples.cpp
JIRA - https://jira.mongodb.org/browse/DOCSP-49686
<li><a href=https://deploy-preview-132--docs-cpp.netlify.app/get-started>get-started</a></li>
https://deploy-preview-132--docs-cpp.netlify.app/read/#find-one
https://deploy-preview-132--docs-cpp.netlify.app/read/retrieve/#find-one-document
> DOCSP-49686: Check for no results before printing

- .github/pull_request_template.md
- README.md
Redirect users to the monorepo.
> [C++] Add monorepo notification
